Implement ToImmutable*Async extension methods
dotnet/reactive pull request #1545
Opened 2021-05-24 19:26 UTC by bash

Resolves #1540.

I copied most of the XML documentation and tests of the non-immutable equivalents (with adjustments of course).

b667720 contains a bit of a refactoring, but I'm not sure if it's a big improvement.

Working with `AsyncOverloads.tt` was a bit of a pain, especially since the generated code has diverged from the generated code (nullability and XML documentation) which meant I had to be careful of what to commit and what to discard.
Wouldn't a source generator be a better fit, because it knows about nullability and generic constraints?

2021-05-24 19:26 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1545) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1545) before we can accept your contribution.<br/><br/>:x: bash [sign now](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1545)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/reactive?pullRequest=1545) it.</sub>

2021-05-24 19:26 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1545) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1545) before we can accept your contribution.<br/><br/>:x: bash [sign now](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1545)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/reactive?pullRequest=1545) it.</sub>

2021-05-26 16:53 UTC, bartdesmet requested changes
LGTM modulo a cosmetic nit around a namespace.

2021-05-26 16:53 UTC, bartdesmet commented on Ix.NET/Source/System.Linq.Async/System/Linq/FunctionalHelpers.cs
> +namespace System.Linq.Async.System.Linq
Clean up the namespace to `System.Linq`. I think this is the by-product of Visual Studio trying to guess the namespace when creating a new `.cs` file in a folder while the `csproj` does not specify some default namespace.

2021-05-26 17:46 UTC, bash commented on Ix.NET/Source/System.Linq.Async/System/Linq/FunctionalHelpers.cs
> +namespace System.Linq.Async.System.Linq
Ah yes I totally missed this 😄. Addressed in 1707045

2021-05-27 03:38 UTC, bartdesmet approved these changes

2021-05-27 03:41 UTC, bartdesmet commented
A source generator could be a viable option to replace the T4. We've had these T4 files for years but as you've observed sometimes manual changes to the .cs files made their way in and slipped through the cracks in code reviews, so we should either do a pass to refresh them, or replace them. In the latter case, we need to make we end up generating the exact same code of course.

2021-08-24 21:27 UTC, bartdesmet commented
@bash I've merged the PR for the source generators (thanks!), so could you go ahead and rebase this PR (due to the delete/edit conflicts for the T4 files which are now obsolete)?

2021-08-25 12:08 UTC, bash commented
@bartdesmet Hurray! I'm really happy how the source generators turned out. This PR is all rebased and ready for another review. 😃

2021-09-15 20:27 UTC, bash commented on Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToImmutableDictionary.cs
> +namespace System.Linq
Yess I finally got around to address your comment 🥳  (and fix my source generator ^^)

Oh, I haven't thought about this! I applied your suggestion for the namespace change and class name change. I also moved the files to match the new namespace.

There's not much that I know about how to best divide up assemblies, but it seems ok to me too to depend on `System.Collections.Immutable` conditionally, if it's only for one target platform.

2022-07-02 22:23 UTC, Romfos commented
one year later -_-

2022-11-16 09:43 UTC, stijnherreman commented
> one year later -_-

Looks like there are no active maintainers currently :(

2022-11-16 10:26 UTC, akarnokd commented
Does this have to live in dotnet/reactive? C# has extension methods so unlike other Rx incarnations, there is no loss of convenience having it in a 3rd party library.

2022-11-16 11:25 UTC, stijnherreman commented
That would hurt discoverability (as pointed out in the PR review), unless it's considered acceptable for a third party library to place things in a `System` namespace?

On the other hand, I wonder if this and the existing mutable methods can be moved to dotnet/runtime instead, now that `IAsyncEnumerable<T>` is available out of the box.

2022-11-16 11:34 UTC, Romfos commented
> Does this have to live in dotnet/reactive? C# has extension methods so unlike other Rx incarnations, there is no loss of convenience having it in a 3rd party library.

I think yes, .NET 6 have this method out of the box for linq

2022-11-16 13:13 UTC, bash commented
I always assumed that the goal of System.Linq.Async is to provide everything for async enumerables that Linq provides for enumerables (Although technically the `ToImmutable*` extension methods are part of `System.Collections.Immutable`).

I'd be willing to move this to a separate project if this should not be part of System.Linq.Async and someone has a good name suggestion for the package :)

2024-08-27 23:27 UTC, bash commented
I'm no longer interested in updating this PR should a maintainer against all odds choose to review it.
Anyone is free to adopt the PR though in that case :)

2024-08-28 13:27 UTC, idg10 commented
/AzurePipelines run

2024-08-28 13:35 UTC, idg10 commented
/AzurePipelines run

2024-08-28 13:47 UTC, merged